# The `common' part is automatically included (and possibly overriden by all
# other flavors)
common:
    # Bucket for storage
    boto_bucket: _env:AWS_S3_BUCKET

    # Amazon S3 Storage Configuration
    s3_access_key: _env:AWS_ACCESS_KEY_ID
    s3_secret_key: _env:AWS_SECRET_ACCESS_KEY
    s3_bucket: _env:AWS_S3_BUCKET
    s3_encrypt: _env:AWS_S3_ENCRYPT
    s3_secure: true

    secret_key: _env:WORKER_SECRET_KEY
    standalone: true

local:
    storage: local
    storage_path: /registry

s3:
    storage: s3
    storage_path: /registry
