#!/bin/sh
set -e -x

cd /docker-registry

if [ -n "$AWS_S3_BUCKET" ] ; then
    export SETTINGS_FLAVOR=s3
else
    export SETTINGS_FLAVOR=local
fi

export WORKER_SECRET_KEY="${WORKER_SECRET_KEY:-$(< /dev/urandom tr -dc A-Za-z0-9 | head -c 32)}"
export AWS_S3_ENCRYPT="${AWS_S3_ENCRYPT:-false}"
export AWS_S3_SECURE="${AWS_S3_ENCRYPT:-true}"

exec gunicorn --access-logfile - --debug --max-requests 100 --graceful-timeout 3600 -t 3600 -k gevent -b 0.0.0.0:5000 -w ${GUNICORN_WORKERS:-4} wsgi:application
