#!/bin/sh
set -e -x

host=${REDIS_HOST:-${REDIS_PORT_6379_TCP_ADDR}}
port=${REDIS_PORT:-${REDIS_PORT_6379_TCP_PORT}}

cmd='exec /usr/bin/redis-cli'

if [ -n "$host" ] ; then
    cmd="$cmd -h $host"
fi

if [ -n "$port" ] ; then
    cmd="$cmd -p $port"
fi

if [ -n "REDIS_PASSWORD" ] ; then
    cmd="$cmd -a $REDIS_PASSWORD"
fi

cmd="$cmd \"\${@}\""

exec su redis -s /bin/sh -c "$cmd" redis-cli-sh "${@}"
