#!/bin/sh
set -e

host=${HOST:-$REDIS_PORT_6379_TCP_ADDR}
port=${PORT:-$REDIS_PORT_6379_TCP_PORT}

flags=''

if [ -n "$host" ] ; then
    flags="$flags -h $host"
fi

if [ -n "$port" ] ; then
    flags="$flags -p $port"
fi

if [ -n "$REDIS_PASSWORD" ] ; then
    flags="$flags -a $REDIS_PASSWORD"
fi

exec /usr/bin/redis-cli $flags "${@}"
