#!/bin/sh
set -e -x

master=''
ulimit -n ${NOFILES:-4096}
if [ -n "$REDIS_MASTER_PORT" ] ; then
    master="--slaveof $(echo "$REDIS_MASTER_PORT" | sed 's,^[a-z-]*:/*,, ; s/:/ /')"
fi

chown redis:redis /var/lib/redis
exec su redis -s /bin/sh -c 'exec /usr/bin/redis-server /etc/redis/redis.conf "${@}"' -- redis-server-sh $master "${@}"
