#!/bin/sh
set -e -x

master=''
if [ -n "$REDIS_MASTER_PORT" ] ; then
    master="--slaveof $REDIS_MASTER_PORT_6379_ADDR $REDIS_MASTER_PORT_6379_PORT"
fi

test -f /var/lib/redis/redis.conf || cp /etc/redis/redis.conf /var/lib/redis/redis.conf

chown -R redis:redis /var/lib/redis
exec chpst -u redis -o ${NOFILES:-4096} \
     /usr/bin/redis-server /var/lib/redis/redis.conf $master "${@}"
