#!/bin/sh
set -e -x

ulimit -n ${NOFILES:-4096}
if [ -z "$REDIS_MASTER_PORT" ] ; then
    master="$(env | awk -F= '/^REDIS_MASTER_(PORT_[0-9]+_TCP_ADDR|IP)=/ { ip=$2 } /^REDIS_MASTER_(PORT_[0-9]+_TCP_)?PORT=/ { port=$2 } END { print "--slaveof", ip, port }')"
else
    master=""
fi

chown redis:redis /var/lib/redis
exec su redis -s /bin/sh -c 'exec /usr/bin/redis-server /etc/redis/redis.conf "${@}"' redis-server-sh $master "${@}"
