#!/bin/sh
set -e -x

whisper_root=/opt/graphite/storage/whisper 
test -d $whisper_root || mkdir -p $whisper_root
chown graphite:graphite $whisper_root
exec /opt/graphite/bin/carbon-cache.py --debug start
