#!/bin/sh
set -e -x

cd /opt/graphite/webapp/graphite

[ -f /opt/graphite/conf/secret ] || openssl rand -base64 64 | tr -d \\n > /opt/graphite/conf/secret
chown root:graphite /opt/graphite/conf/secret
chmod 0640 /opt/graphite/conf/secret

python2.7 manage.py syncdb --noinput
chown graphite:graphite /opt/graphite/storage/graphite.db

exec /usr/local/bin/gunicorn_django -u graphite -g graphite -b 0.0.0.0:8080 /opt/graphite/webapp/graphite/settings.py
